name: shishra
description: "A new Nowa project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  another_flushbar: ^1.12.30
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  pinput: ^5.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  uuid: ^4.4.0
  flutter_svg: ^2.0.10
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/