// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4o0Jr52qSSarRw31H5GVwXtNuG7Ef3M',
    appId: '1:742795963144:web:373f80372609c533405abd',
    messagingSenderId: '742795963144',
    projectId: 'shishra',
    authDomain: 'shishra.firebaseapp.com',
    storageBucket: 'shishra.firebasestorage.app',
    measurementId: 'G-MVD1H3395B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgl563-vIGKeSFssalHs-x0GQFnQBaf6I',
    appId: '1:742795963144:android:bcd130517ab11947405abd',
    messagingSenderId: '742795963144',
    projectId: 'shishra',
    storageBucket: 'shishra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8P5_GBS0k9OOl0IFlZhRUpw9IKtMGQg',
    appId: '1:742795963144:ios:ee92330e88eea0e6405abd',
    messagingSenderId: '742795963144',
    projectId: 'shishra',
    storageBucket: 'shishra.firebasestorage.app',
    iosBundleId: 'com.example.shishra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8P5_GBS0k9OOl0IFlZhRUpw9IKtMGQg',
    appId: '1:742795963144:ios:ee92330e88eea0e6405abd',
    messagingSenderId: '742795963144',
    projectId: 'shishra',
    storageBucket: 'shishra.firebasestorage.app',
    iosBundleId: 'com.example.shishra',
  );
}
